apiVersion: v1
appVersion: 1.5.2
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: gs-serving-web-content
version: 1.5.2
